name: Publish to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [rubocop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SHOPUS_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          ssh-keyscan -H 208.113.200.130 >> ~/.ssh/known_hosts

      - name: Deploy changes
        run: |
          # Connect to the server via SSH and pull changes
          ssh -i ~/.ssh/deploy_key.pem ubuntu@208.113.200.130 'cd /var/www/products-api && git pull origin main && bundle install && bundle exec rake db:migrate && sudo service nginx restart'

      - name: Cleanup SSH keys
        run: |
          rm ~/.ssh/deploy_key.pem
          rm ~/.ssh/known_hosts
